// Regenerates lib/abi.ts from the Foundry build output of the contracts repo.
// Usage: CRYPTOWILL_CONTRACTS_DIR=../cryptowill pnpm sync-abi   (run `forge build` there first)
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const contractsDir = resolve(process.env.CRYPTOWILL_CONTRACTS_DIR ?? "../cryptowill");
const artifact = JSON.parse(
  readFileSync(resolve(contractsDir, "out/CryptoWill.sol/CryptoWill.json"), "utf8"),
);

const out = `// Generated by scripts/sync-abi.mjs from ${"cryptowill/out/CryptoWill.sol/CryptoWill.json"}. Do not edit.
export const cryptoWillAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;
writeFileSync(resolve("lib/abi.ts"), out);
console.log(`lib/abi.ts: ${artifact.abi.length} ABI entries from ${contractsDir}`);
